"""bug-fix

Revision ID: 504598510955
Revises: a4636146a1f0
Create Date: 2023-12-13 18:56:57.852403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504598510955'
down_revision: Union[str, None] = 'a4636146a1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('bookings_users_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.drop_column('bookings', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_users_id_fkey', 'bookings', 'users', ['users_id'], ['id'])
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
